### ISSUE TITLE
project-dir not honored if building for both iOS and Android from a single task

### ISSUE THREAD

**Issue by skypanther** [sharpred/grunt-appc-cli#13]
I'm kinda grasping at straws here. I'm not sure that this is a bug of this module, probably in my gruntfile. But I can't figure it out and I'm hoping maybe you've seen something like this. 

I have a complex grunt script that:

* creates a temporary directory
* copies my project to it
* copies in the correct tiapp.xml and config.json file depending on my target (ad-hoc/testing vs production)
* builds from that temp directory
* deletes the temp directory in the end

I have a task that does all of the above for just ios, one for just android, and one for both platforms at once. Both the ios and android build scripts work fine on their own. But, the combined one fails after building for the first platform with an error indicating that I'm "not in a project directory." If I swap which platform is built first, whichever is listed first builds fine. The second platform build always fails.

As you can see below, I'm specifying the `--project-dir` (absolute path is used in the below but I've tried with relative ones). I've tweaked this grunt plugin to output the appc command it's executing and it looks correct. In fact, I can run that command without errors. But when run from the script, it's just not honoring that project-dir argument for the second build platform.

(I've tried with both `appc run` and `appc ti build` as shown below; same issue with either.)

```
'appc-cli': {
  'options': {},
  'ios': {
    "command": "ti",
    "subcommand": "build",
    "args": ["--project-dir", path.join(path.resolve('.'), 'tmpBuildDir'), "-p", "ios", "-T", "dist-adhoc", "-R", '<%= settings.distributionName %>', "--pp-uuid", '<%= settings.ppUuid %>', "-O", './dist', "--build-only"]
  },
  'appstore': {
    "command": "ti",
    "subcommand": "build",
    "args": ["--project-dir", path.join(path.resolve('.'), 'tmpBuildDir'), "-p", "ios", "-T", "dist-appstore", "-R", '<%= settings.distributionName %>', "--pp-uuid", '<%= settings.ppUuidAppstore %>']
  },
  'android': {
    "command": "ti",
    "subcommand": "build",
    "args": ["--project-dir", path.join(path.resolve('.'), 'tmpBuildDir'), "-p", "android", "-T", "dist-playstore", "-K", '<%= settings.keystoreLocation %>', "-P", '<%= settings.storePassword %>', "-O", './dist', "--build-only"]
  },
},
```

Any thoughts? 

My whole gruntscript is at https://gist.github.com/skypanther/0ba583d485335baabe276947a526bc8a

**Comment by sharpred** [comment]
Hi Tim

I have done quite a lot of projects doing stuff like this, swapping in and out of temp directories etc. so would be reasonably confident it is not my plugin doing this.

The main difference with what I do is that I prefer to use grunt.file operations for stuff like this.  I have done a small gist for you that outlines how I would do it.  Am travelling at the moment, so YMMV and all that, but it is based on a real project with live iOS and Android apps.

The Gist is here https://gist.github.com/sharpred/3276afd6c4b3ff98fc5e7438315f42f8

You will notice that I like to keep my Gruntfile as light as possible and have a separate tasks folder with all my individual jobs in, that I load and initialise in Gruntfile.js

Let me know how it goes, can dig it a little deeper if this does not help you.

**Comment by skypanther** [comment]
Wonderful, thanks! I will try restructuring my grunt file. It has grown and bloated over the life of this project for sure.

**Comment by sharpred** [comment]
can we close this?

**Comment by skypanther** [comment]
Sure, I never got my grunt script working and restructuring just added more bugs to track down. But, it's obviously not a problem with this project.
