### ISSUE TITLE
NPM/package.json points to wrong repo

### ISSUE THREAD

**Issue by skypanther** [sharpred/grunt-appc-cli#3]
The project links on https://www.npmjs.com/package/grunt-appc-cli point to a non-existent repo and should point to this repo instead. This is because of the values you have listed in your package.json.

https://github.com/sharpred/grunt-appc-cli/blob/master/package.json

Hitting a bunch of 404s made me a little uneasy about installing your NPM module. Would you update those references and republish to NPM?

**Comment by sharpred** [comment]
thanks for pointing this out, now fixed
